// Code generated by L-ctl.

package {{.pkg}}

import (
    {{if .time}}"time"{{end}}
    {{if .decimal}}"github.com/shopspring/decimal"{{end}}
)

type {{.objectName}} struct {
    {{range .fields}}{{.name}} {{.type}} {{.tag}} {{if .hasComment}}// {{.comment}}{{end}}
    {{end}}
}

func (t *{{.objectName}}) TableName() string {
    return "{{.tableName}}"
}