// Code generated by L-ctl. DO NOT EDIT.

package {{.pkg}}

import (
    {{if .time}}"time"{{end}}
    {{if .decimal}}"github.com/shopspring/decimal"{{end}}
)

type {{.objectName}} struct {
    {{range .fields}}{{.name}} {{.type}} {{.tag}} {{if .hasComment}}// {{.comment}}{{end}}
    {{end}}
}
