// Code generated by L-ctl.

package {{ .Pkg }}

// {{ .GroupValue }}
const (
    {{ range .Enums }}{{ .Key }} = "{{ .Value }}" // {{ .Comment }}
    {{ end }}
)

func Description(value string) string {
    switch value {
    {{ range .Enums }}case "{{ .Value }}":
        return = "{{ .Comment }}"
    {{ end }}
    default:
        return ""
    }
}