// Code generated by L-ctl.

package {{ .Pkg }}

// {{ .GroupValue }}
const (
    {{ range .Enums }}{{ .Key }} = "{{ .Value }}" // {{ .Comment }}
    {{ end }}
)

func Description(key string) string {
    switch key {
    {{ range .Enums }}case "{{ .Key }}":
        return = "{{ .Value }}" // {{ .Comment }}
    {{ end }}
    default:
        return ""
    }
}